### ISSUE TITLE
Wait before restarting an unhealty container

### ISSUE THREAD

**Issue by david-vicente** [tmknight/docker-autoheal#110]
The current docker-autoheal instantaneous stops the container when it fails the healthchecks and is marked unhealthy. Is there a way to make it wait for some period before stopping the container?

This might be useful in the setting where you have replicas of a service behind a reverse proxy/load balance. If one of the replicas gets unhealthy, you might want the reverse proxy to remove that service from the load balance pool (so that it doesn't receive new requests), but still want to wait for an additional period to see if service is able to return to healthy by itself (and possibly complete a long running request) before killing it.

**Comment by tmknight** [comment]
That is for the healthcheck configuration itself - you need to adjust that.  The tool triggers off of unhealthy - what unhealthy means is up to you.

**Comment by david-vicente** [comment]
In my example, the reverse proxy also triggers off of unhealthy. Both would use the same trigger, but docker-autoheal would give the reverse proxy some time to adapt.

**Comment by tmknight** [comment]
Again, you should adjust your health-check to accommodate your scenario

**Comment by david-vicente** [comment]
I don't understand what you mean... The unhealthy label is a property of the container. I can't change that.

**Comment by tmknight** [comment]
Of course you can: https://docs.docker.com/reference/dockerfile/#healthcheck

**Comment by david-vicente** [comment]
My healthcheck command is working as intended. A service stops responding and after failing to respond in all retries it is marked as `unhealthy`. Now, this is where other services (like docker-autoheal or traefik) might act, triggering on `unhealthy`. What I'm asking for is some variable like `AUTOHEAL_RESTART_GRACE_PERIOD`, so that docker-autoheal triggers on unhealthy but waits some time, which would be defined by that variable, before restarting. I don't see how I can do that by tweaking Docker's healthcheck, or the command I tell Docker to run in order to check if the containers are responding or not.

**Comment by david-vicente** [comment]
Maybe I'm missing something obvious. I'm all ears, if you have any suggestion.

**Comment by joost471** [comment]
I have the same request. My use case is the following: 
I'm using gluetun as a vpn container and a second container depends on gluetun. When gluetun loses connectivity, it goes unhealthy is restarts itself. So far, so good. 
The problem is that, when gluetun is restarted, the dependent container is not restarted and does not regain network connectivity. If I add a healtcheck to the second container and enable autoheal, docker-autoheal restarts the container immediately. But gluetun is not back up and running, and because the container depends on gluetun to be up, it fails to start.
So, in this case, eg a `AUTOHEAL_RESTART_GRACE_PERIOD` setting would help. 

How it would work: 
- gluetun goes unhealthy and auto-restarts
- the healtcheck of the dependent container fails and goes unhealthy. Triggering the grace_period (lets say: 10sec) and not immediately restarting
- gluetun comes back up after 5 sec
- after another 5 sec: the grace_period expired and docker-autoheal restarts the dependent container

I know this isn't a complete bulletproof sollution. Eg: If gluetun takes more than 10 sec to restart, the restart of the second container will still fail. But than we just have to increase the grace_period.
